# My variables
name: verma / blog
description: verma's blog
google_analytics: UA-53963462-1
google_verification: null
permalink: pretty


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
