# Site settings
title: verma/blog
email: uday.karan@gmail.com
author: Uday Verma
description: "Super awesome kung-fu maestah"
url: http://udayv.com/
# Build settings
markdown: kramdown
permalink: pretty
paginate: 6
